### ISSUE TITLE
The playground is buggy recently upon redeploy of contracts

### ISSUE THREAD

**Issue by Bamthelearner** [onflow/flow-playground#234]
**Describe the bug**
The playground error report pop-up window will become really buggy after contract redeployment.

**To Reproduce**
1. Draft a contract under any of the account.
2. deploy the contract
3. draft a transaction / script that will interact with the contract
4. go back to the contract and add new functions / variables
5. redeploy the contract
6. please dont hit F5 after the redeployment
7. go back to the transaction / script and key in the new function / variable, the playground will return : no member in contract.

**Expected behavior**
It is expected the pop-up window will show no error as the contract is already updated and redeployed.

**Screenshots**
![image](https://user-images.githubusercontent.com/95492891/156803077-c54b72b1-a1ea-47c4-b8d6-380d17ae9dd3.png)
![image](https://user-images.githubusercontent.com/95492891/156803173-f02907bb-198b-4f00-9cd5-cba5056c8d1c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 98.0

**Comment by Bamthelearner** [comment]
Sorry for not having the screen shot that demonstrate perfectly the issue
Most bugs can be solved with 1 - 2 F5, but that is not really friendly as sometimes F5 washes away users work.

**Comment by Bamthelearner** [comment]
Just now I found that the pop-up window is reporting errors with numbers not in order.
![image](https://user-images.githubusercontent.com/95492891/156918798-7b2ff5a8-e942-4576-bac9-ad77ff662e1d.png)

All I did is just first go to 0x02's account, import contract from 0x01 and then changes some code under 0x02's contract.

The order of the errors will be in mess and might repeat itself.

**Comment by MaxStalker** [comment]
Thank you for reporting the issue. @Bamthelearner 
This was probably due to latest updates to language client and server. I will try to fix this one asap :sweat_smile: 
Sorry for inconvenience :bow:

**Comment by Bamthelearner** [comment]
Thank you @MaxStalker 
Please dont be sorry, we all just want to better the experience on flow!

**Comment by MaxStalker** [comment]
Hey, @Bamthelearner !
We've encountered several issues with language server/client communication. Most of them were fixed and I believe your case was covered as well.

Can you check one more time and report if anything else is not working? 😅

**Comment by kelcoinec** [comment]
It's much better now, though it still happens to press F5 once in a while. Thanks!

**Comment by MaxStalker** [comment]
We've decided to dig dipper and pin point the problems for all of those errors. As a result we are preparing a major refactoring of app code for better orchestration of data flow between language client, server and monaco editor. Which should result in a much smoother and error-free performance.

Current work is gathered under #238

**Comment by kerrywei** [comment]
@MaxStalker can you provide status updates?

**Comment by MaxStalker** [comment]
Improved version is currently deployed to https://play.onflow.org

@Bamthelearner @kelcoinec can you guys play around with it and say if you find any problems? :)
